version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  api:
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/app
    command: bash -c "alembic upgrade head && ./app/prestart.sh && exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
