"""Add script model

Revision ID: 30575c556d9f
Revises: 941fbca3fe1e
Create Date: 2022-06-03 00:12:37.212156

"""
from alembic import op
import sqlalchemy as sa
from app.db.sqlalchemy import GUID


# revision identifiers, used by Alembic.
revision = '30575c556d9f'
down_revision = '941fbca3fe1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_worker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', GUID(), nullable=True),
    sa.Column('dt_create', sa.DateTime(), nullable=True),
    sa.Column('dt_update', sa.DateTime(), nullable=True),
    sa.Column('script', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_worker')
    # ### end Alembic commands ###
