"""Add currency

Revision ID: 941fbca3fe1e
Revises: 5482918985f5
Create Date: 2022-06-01 14:32:21.450222

"""
from alembic import op
import sqlalchemy as sa
from app.db.sqlalchemy import GUID


# revision identifiers, used by Alembic.
revision = '941fbca3fe1e'
down_revision = '5482918985f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', GUID(), nullable=True),
    sa.Column('dt_create', sa.DateTime(), nullable=True),
    sa.Column('dt_update', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('iso', sa.String(length=5), nullable=True),
    sa.Column('price', sa.Float(precision=8, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('currency_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', GUID(), nullable=True),
    sa.Column('dt_create', sa.DateTime(), nullable=True),
    sa.Column('dt_update', sa.DateTime(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=8, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_price_history')
    op.drop_table('currency')
    # ### end Alembic commands ###
